[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stageflow-framework"
version = "0.9.0"
description = "StageFlow: pipeline framework for stages"
readme = "README.md"
authors = [
    { name = "lethargy" }
]
dependencies = [
    "pyyaml",
    "jsonschema>=4.0.0",
    "immutables>=0.20",
    "common-expression-language>=0.9",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "flake8",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["stageflow*"]

[tool.setuptools.package-data]
"stageflow" = ["py.typed", "docs/schemas/pipeline.json"]
