"""StageFlow — фреймворк описания и исполнения JSON-пайплайнов.

Публичный API пакета: всё, что нужно пользователю фреймворка, импортируется
отсюда — ``from stageflow import Pipeline, Session, BaseStage, ...``.
Импорт ``stageflow.builtins`` регистрирует встроенные стадии.
"""
from . import builtins  # noqa: F401 - регистрирует встроенные стадии
from .core import (
    BaseStage,
    CelEngine,
    CelError,
    ConditionNode,
    Context,
    EntryNode,
    Event,
    EventSpec,
    InputSpec,
    Node,
    ParallelNode,
    Pipeline,
    Retrier,
    Session,
    SessionResult,
    StepDebugger,
    StageNode,
    SubPipelineNode,
    SwitchNode,
    TerminalNode,
    TryNode,
    ExceptHandler,
    TypeRegistry,
    TypeSystem,
    get_node_types,
    get_stage,
    get_stages,
    get_stages_by_category,
    parse_type,
    register_node,
    register_stage,
)
from .docs import generate_stages_json, generate_stages_yaml
from .exceptions import (
    ArtifactNotFoundError,
    BranchError,
    ExpressionError,
    PayloadValidationError,
    PipelineDefinitionError,
    PipelineValidationError,
    RegistryError,
    StageContractError,
    StageFlowError,
    StageOutputError,
    TypeCheckError,
    TypeDeclarationError,
)

__all__ = [
    # ядро
    "Pipeline",
    "Session",
    "SessionResult",
    "StepDebugger",
    "Context",
    "BaseStage",
    "register_stage",
    "get_stage",
    "get_stages",
    "get_stages_by_category",
    "Node",
    "register_node",
    "get_node_types",
    "EntryNode",
    "StageNode",
    "ConditionNode",
    "SwitchNode",
    "ParallelNode",
    "SubPipelineNode",
    "TerminalNode",
    "Retrier",
    "TryNode",
    "ExceptHandler",
    "Event",
    "EventSpec",
    "InputSpec",
    "CelEngine",
    "CelError",
    # типизация переменных
    "TypeSystem",
    "TypeRegistry",
    "parse_type",
    # документация
    "generate_stages_yaml",
    "generate_stages_json",
    # исключения
    "StageFlowError",
    "RegistryError",
    "PipelineDefinitionError",
    "PipelineValidationError",
    "ExpressionError",
    "PayloadValidationError",
    "StageContractError",
    "StageOutputError",
    "ArtifactNotFoundError",
    "BranchError",
    "TypeDeclarationError",
    "TypeCheckError",
]
